#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Claude-inspired styling colors
ORANGE='\033[0;33m'
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${ORANGE}🚀 Initializing gitGate Installation Pipeline...${NC}"

# 1. Look for the local Git directory
HOOKS_DIR=".git/hooks"

if [ ! -d "$HOOKS_DIR" ]; then
    echo -e "${RED}❌ Error: The current folder is not a git repository.${NC}"
    echo "   Please navigate to your target project folder and run 'git init' first."
    exit 1
fi

# 2. Setup the global directory structure in the home folder (~/.gitgate)
GLOBAL_DIR="$HOME/.gitgate"
mkdir -p "$GLOBAL_DIR"

echo "📦 Fetching files from github.com/vijayhiremath01/gitGate..."

# 3. Download the core scripts directly from your public GitHub repository
curl -fsSL "https://raw.githubusercontent.com/vijayhiremath01/gitGate/main/gitgate.py" -o "$GLOBAL_DIR/gitgate.py"
curl -fsSL "https://raw.githubusercontent.com/vijayhiremath01/gitGate/main/review_rules.md" -o "$GLOBAL_DIR/review_rules.md"

# 4. Handle Python environment isolation locally inside the global folder
if [ ! -d "$GLOBAL_DIR/venv" ]; then
    echo "⚙️ Setting up Python isolated dependencies..."
    python3 -m venv "$GLOBAL_DIR/venv"
    "$GLOBAL_DIR/venv/bin/pip" install --quiet groq rich
fi

# 5. Inject the auto-trigger into the local project hook pipeline
cat << 'EOF' > "$HOOKS_DIR/pre-commit"
#!/bin/bash

# Auto-generated by gitGate Installer
exec < /dev/tty

GLOBAL_DIR="$HOME/.gitgate"
SCRIPT_PATH="$GLOBAL_DIR/gitgate.py"
VENV_PYTHON="$GLOBAL_DIR/venv/bin/python"

if [ -f "$SCRIPT_PATH" ]; then
    "$VENV_PYTHON" "$SCRIPT_PATH"
else
    echo "⚠️ gitGate engine not found at $SCRIPT_PATH. Skipping review."
    exit 0
fi
EOF

# 6. Make the pre-commit script executable by the system
chmod +x "$HOOKS_DIR/pre-commit"

echo -e "${GREEN}✅ Success! gitGate is now automatically configured for this repository.${NC}"
echo "   Every 'git commit' will run your senior agent review line-by-line."